### ISSUE TITLE
Can't open the 1.3.0 version or any above

### ISSUE THREAD

**Issue by NukedFox** [Lemonszz/Biome-Makeover#47]
When i try to install any version of this mod in the 1.3.0 version or above, I play in the 1.16.4 version of the fabric API, the game crashes and sends me this message:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/05/21 04:47 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'biomemakeover'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/entity/event/v1/ServerEntityCombatEvents
	at party.lemons.biomemakeover.world.BMWorldEvents.init(BMWorldEvents.java:78)
	at party.lemons.biomemakeover.BiomeMakeover.onInitialize(BiomeMakeover.java:66)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2522/2099280878.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.entity.event.v1.ServerEntityCombatEvents
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Thanks!

**Comment by NukedFox** [comment]
I think it is a silly mistake of mine, I'm new programming so if anyone can help me i'd be very thankful.

**Comment by Lemonszz** [comment]
Make sure you're using the latest version of Fabric API. 

Any particular reason you're on 1.16.4? Most if not all 1.16.4 mods should work on 1.16.5.

**Comment by NukedFox** [comment]
> 
> 
> Make sure you're using the latest version of Fabric API.
> 
> Any particular reason you're on 1.16.4? Most if not all 1.16.4 mods should work on 1.16.5.

**Comment by NukedFox** [comment]
Ok, thanks!
